/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package smule;

import io.appium.java_client.AppiumDriver;
import org.testng.annotations.*;
import smule.pages.Login.LoginPage;

import java.time.Duration;

import static org.testng.Assert.*;

public class LoginTest {
    AppiumDriver androidDriver;
    @BeforeClass
    public void setUp() {
        androidDriver = new BasePage().getDriver();
        androidDriver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    }
    @Test public void shouldLogin() {
        LoginPage loginPage = new LoginPage();
        loginPage.selectLanguage();
        loginPage.confirmLanguage();
        loginPage.signInWithGoogle();
    }
}
