/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package smule;

import io.appium.java_client.AppiumDriver;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import smule.pages.Login.LoginPage;
import utils.ConfigLoader;
import utils.FilePaths;

import java.time.Duration;
import java.util.Map;

public class LoginTest {
    AppiumDriver androidDriver;
    Map credentials = new ConfigLoader().getJSON(FilePaths.CREDENTIALS);
    @BeforeClass
    public void setUp() {
        androidDriver = new BasePage().getDriver();
        androidDriver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    }
    @Test public void shouldLogin() {
        LoginPage loginPage = new LoginPage();
        loginPage.selectLanguage();
        loginPage.confirmLanguage();
        loginPage.signInWithEmail();
        loginPage.enterCredentials((String)credentials.get("email"),(String)credentials.get("password"));
    }
}
