/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package smule;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import utils.ConfigLoader;

import java.net.URL;
import java.time.Duration;

public class BasePage {
    public static AppiumDriver driver;

    public AppiumDriver getDriver() {
        ConfigLoader configLoader = new ConfigLoader();
        DesiredCapabilities capabilities = new DesiredCapabilities(configLoader.getCapability());
        try {
            if (driver == null) {
                driver = new AndroidDriver(new URL("http://localhost:4723/wd/hub/"), capabilities);
                driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
            }
        } catch (Exception e) {
            System.out.println("Exception caught : " + e.getLocalizedMessage());
        }
        return driver;
    }
}
