/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package smule;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;

import java.net.MalformedURLException;
import java.net.URL;

public class BasePage {
    private AndroidDriver<MobileElement> driver = null;
    public AppiumDriver<MobileElement> getDriver() throws MalformedURLException {
        if(driver!= null){
            driver = new AndroidDriver<MobileElement>(new URL("http://localhost:4723/wd/hub"), null);
        }
        return driver;
    }
}
